package org.qortal.test;

import org.junit.Test;
import org.qortal.network.message.PingMessage;
import org.qortal.network.message.MessageException;

import static org.junit.Assert.*;

public class PeerBufferAndMessageSerializationTests {

	@Test
	public void testMessageSerializationCaching() throws MessageException {
		PingMessage message = new PingMessage();
		byte[] bytes1 = message.toBytes();
		assertNotNull("Serialized bytes should not be null", bytes1);
		assertTrue("Serialized bytes should have length > 0", bytes1.length > 0);

		byte[] bytes2 = message.toBytes();
		assertSame("Repeated calls to toBytes() should return cached byte array reference", bytes1, bytes2);

		// Changing ID invalidates cached bytes
		message.setId(12345);
		byte[] bytes3 = message.toBytes();
		assertNotNull("Serialized bytes after ID change should not be null", bytes3);
		assertNotSame("Bytes after setId should be a newly generated byte array", bytes1, bytes3);

		byte[] bytes4 = message.toBytes();
		assertSame("Subsequent calls to toBytes() should return new cached byte array reference", bytes3, bytes4);
	}
}
