package org.qortal.test.crosschain;
import org.junit.Test;
import static org.junit.Assert.*;
import org.bitcoinj.core.*;
import org.bitcoinj.crypto.DeterministicKey;
import org.qortal.crosschain.*;
import com.google.common.hash.HashCode;
import com.fasterxml.jackson.databind.ObjectMapper;
import pirate.wallet.sdk.rpc.CompactFormats.CompactBlock;
import java.util.*;

/** Offline cross-language fixtures generated by Hub's local signer; keys are test-only. */
public class LocalWalletTests extends org.qortal.test.common.Common {
    private static final Map<String, NetworkParameters> PARAMS = Map.of(
        "BTC", Bitcoin.BitcoinNet.MAIN.getParams(), "LTC", Litecoin.LitecoinNet.MAIN.getParams(),
        "DOGE", Dogecoin.DogecoinNet.MAIN.getParams(), "DGB", Digibyte.DigibyteNet.MAIN.getParams(),
        "RVN", Ravencoin.RavencoinNet.MAIN.getParams());
    private Map<String, String> fixture(String coin) throws Exception {
        return new ObjectMapper().readValue(getClass().getResourceAsStream("/crosschain/local-wallet/" + coin + ".json"), Map.class);
    }
    @Test public void verifyHubSignaturesForEveryCoin() throws Exception {
        for (String coin : PARAMS.keySet()) {
            Map<String, String> f = fixture(coin);
            NetworkParameters params = PARAMS.get(coin);
            Context.propagate(new Context(params));
            Transaction funding = new Transaction(params, HashCode.fromString(f.get("previous")).asBytes());
            Transaction spend = new Transaction(params, HashCode.fromString(f.get("raw")).asBytes());
            spend.verify();
            assertEquals(f.get("txId"), spend.getTxId().toString());
            spend.getInput(0).verify(funding.getOutput(0));
            assertEquals(10000, funding.getOutput(0).getValue().value - spend.getOutput(0).getValue().value);
            // The signature must bind the exact amount approved in Hub.
            spend.getOutput(0).setValue(Coin.valueOf(spend.getOutput(0).getValue().value - 1));
            try { spend.getInput(0).verify(funding.getOutput(0)); fail("Modified payment verified"); }
            catch (org.bitcoinj.script.ScriptException expected) { }
        }
    }
    @Test public void discoveryRejectsPrivateKeysAndMismatchedChains() throws Exception {
        Map<String, String> f = fixture("LTC");
        FakeProvider provider = new FakeProvider(f);
        FakeCoin coin = new FakeCoin(provider);
        String chain = "bip122:12a765e31ffd4059bada1e25190f6e98";
        String xpub = DeterministicKey.deserializeB58(f.get("xprv"), PARAMS.get("LTC")).serializePubB58(PARAMS.get("LTC"));
        try { LocalWalletSupport.spendContext(coin, f.get("xprv"), chain); fail("Private key accepted"); }
        catch (IllegalArgumentException expected) { }
        assertEquals(0, provider.reads);
        try { LocalWalletSupport.spendContext(coin, xpub, "bip122:wrong"); fail("Wrong chain accepted"); }
        catch (IllegalArgumentException expected) { }
        Map<String, Object> result = LocalWalletSupport.spendContext(coin, xpub, chain);
        List<Map<String, Object>> outputs = (List<Map<String, Object>>) result.get("utxos");
        assertEquals(1, outputs.size());
        assertEquals("Both branches retain the full 20-address gap", 41, provider.reads);
        assertEquals("Only the used address needs an unspent-output query", 1, provider.unspentReads);
        assertEquals(List.of(0, 0), outputs.get(0).get("path"));
        assertEquals("1000000000", outputs.get(0).get("value"));
        assertFalse(new ObjectMapper().writeValueAsString(result).contains(f.get("xprv")));
        provider.tamper = true;
        try { LocalWalletSupport.spendContext(coin, xpub, chain); fail("Forged value accepted"); }
        catch (ForeignBlockchainException expected) { }
        assertEquals("A second scan must fetch current outputs again", 2, provider.unspentReads);
    }
    @Test public void broadcastChecksChainAndForwardsExactlySignedBytes() throws Exception {
        Map<String, String> f = fixture("LTC"); FakeProvider provider = new FakeProvider(f); FakeCoin coin = new FakeCoin(provider);
        String chain = "bip122:12a765e31ffd4059bada1e25190f6e98";
        assertEquals(f.get("txId"), LocalWalletSupport.broadcast(coin, f.get("raw"), chain));
        assertEquals(f.get("raw"), provider.broadcast);
        try { LocalWalletSupport.broadcast(coin, "nothex", chain); fail(); } catch (IllegalArgumentException expected) { }
        try { LocalWalletSupport.broadcast(coin, f.get("raw"), "wrong"); fail(); } catch (IllegalArgumentException expected) { }
    }
    @Test public void localTradePreparationIsDurableWatchOnlyAndIdempotent() throws Exception {
        org.qortal.utils.NTP.setFixedOffset(0L);
        Map<String, String> f = fixture("LTC");
        FakeCoin coin = new FakeCoin(new FakeProvider(f));
        String xpub = DeterministicKey.deserializeB58(f.get("xprv"), PARAMS.get("LTC")).serializePubB58(PARAMS.get("LTC"));
        org.qortal.data.crosschain.CrossChainTradeData offer = new org.qortal.data.crosschain.CrossChainTradeData();
        offer.qortalAtAddress = "AT-test-local-funding";
        offer.foreignBlockchain = "LITECOIN";
        offer.tradeTimeout = 60;
        offer.expectedForeignAmount = 100000000L;
        offer.qortAmount = 100000000L;
        offer.creatorForeignPKH = new byte[20];
        offer.mode = AcctMode.OFFERING;
        String receiver = org.qortal.test.common.Common.getTestAccount(null, "alice").getAddress();
        try (org.qortal.repository.Repository repository = org.qortal.repository.RepositoryManager.getRepository()) {
            Map<String, Object> first = org.qortal.controller.tradebot.LocalTradeFunding.prepare(repository, LitecoinACCTv3.getInstance(), offer, xpub, receiver, coin);
            Map<String, Object> second = org.qortal.controller.tradebot.LocalTradeFunding.prepare(repository, LitecoinACCTv3.getInstance(), offer, xpub, receiver, coin);
            assertEquals(first, second);
            assertEquals("100001000", first.get("amount"));
            assertFalse(new ObjectMapper().writeValueAsString(first).contains(f.get("xprv")));
            List<org.qortal.data.crosschain.TradeBotData> entries = repository.getCrossChainRepository().getAllTradeBotData();
            assertEquals(1, entries.size());
            org.qortal.data.crosschain.TradeBotData data = entries.get(0);
            assertEquals(xpub, data.getForeignKey());
            assertEquals(80, data.getStateValue());
            // A crash after sending the offer must not force a refund if the AT
            // already locked to this buyer. Resume the existing AT-lock handler.
            offer.mode = AcctMode.TRADING;
            org.qortal.controller.tradebot.LocalTradeFunding.progress(repository, data, offer, coin);
            assertEquals(85, data.getStateValue());
        }
    }
    static class FakeCoin extends Bitcoiny {
        FakeCoin(FakeProvider p) { super(p, new Context(PARAMS.get("LTC")), "LTC", Coin.valueOf(10000)); }
        public long getP2shFee(Long at) { return 1000; }
        public long getFeeRequired() { return 1000; }
        public void setFeeRequired(long fee) { }
    }
    static class FakeProvider extends BitcoinyBlockchainProvider {
        final byte[] raw; final Transaction tx; int reads; int unspentReads; boolean tamper; String broadcast;
        FakeProvider(Map<String, String> fixture) { raw = HashCode.fromString(fixture.get("previous")).asBytes(); tx = new Transaction(PARAMS.get("LTC"), raw); }
        public String getNetId() { return "Litecoin-MAIN"; }
        public int getCurrentHeight() { return 200; }
        public List<TransactionHash> getAddressTransactions(byte[] scriptPubKey, boolean includeUnconfirmed) { reads++; return Arrays.equals(scriptPubKey, tx.getOutput(0).getScriptBytes()) ? List.of(new TransactionHash(100, tx.getTxId().toString())) : List.of(); }
        public List<UnspentOutput> getUnspentOutputs(byte[] scriptPubKey, boolean includeUnconfirmed) { unspentReads++; return Arrays.equals(scriptPubKey, tx.getOutput(0).getScriptBytes()) ? List.of(new UnspentOutput(tx.getTxId().getBytes(), 0, 100, tamper ? 1 : 1000000000)) : List.of(); }
        public byte[] getRawTransaction(byte[] txHash) { return raw; }
        public void broadcastTransaction(byte[] bytes, String expected) { broadcast = HashCode.fromBytes(bytes).toString(); }
        @Override public void setBlockchain(Bitcoiny blockchain) { throw new UnsupportedOperationException(); }
        @Override public List<CompactBlock> getCompactBlocks(int startHeight, int count) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public List<byte[]> getRawBlockHeaders(int startHeight, int count) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public List<Long> getBlockTimestamps(int startHeight, int count) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public long getConfirmedBalance(byte[] scriptPubKey) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public long getConfirmedAddressBalance(String base58Address) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public byte[] getRawTransaction(String txHash) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public BitcoinyTransaction getTransaction(String txHash) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public List<BitcoinyTransaction> getAddressBitcoinyTransactions(String address, boolean includeUnconfirmed) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public List<UnspentOutput> getUnspentOutputs(String address, boolean includeUnconfirmed) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public void broadcastTransaction(byte[] rawTransaction) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public Set<ChainableServer> getServers() { throw new UnsupportedOperationException(); }
        @Override public Set<ChainableServer> getUselessServers() { throw new UnsupportedOperationException(); }
        @Override public ChainableServer getCurrentServer() { throw new UnsupportedOperationException(); }
        @Override public boolean addServer( ChainableServer server ) { throw new UnsupportedOperationException(); }
        @Override public boolean removeServer( ChainableServer server ) { throw new UnsupportedOperationException(); }
        @Override public Optional<ChainableServerConnection> setCurrentServer(ChainableServer server, String requestedBy) throws ForeignBlockchainException { throw new UnsupportedOperationException(); }
        @Override public List<ChainableServerConnection> getServerConnections() { throw new UnsupportedOperationException(); }
        @Override public ChainableServer getServer(String hostName, ChainableServer.ConnectionType type, int port) { throw new UnsupportedOperationException(); }
    }
}
